/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as HowRouteImport } from './routes/how'
import { Route as IndexRouteImport } from './routes/index'
import { Route as STokenRouteImport } from './routes/s.$token'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedClassesIdRouteImport } from './routes/_authenticated/classes.$id'
import { Route as AuthenticatedClassesIdIndexRouteImport } from './routes/_authenticated/classes.$id.index'
import { Route as AuthenticatedClassesIdConfigsConfigIdRouteImport } from './routes/_authenticated/classes.$id.configs.$configId'
import { Route as AuthenticatedClassesIdConfigsConfigIdIndexRouteImport } from './routes/_authenticated/classes.$id.configs.$configId.index'
import { Route as AuthenticatedClassesIdConfigsConfigIdRunsRunIdRouteImport } from './routes/_authenticated/classes.$id.configs.$configId.runs.$runId'
import { Route as AuthenticatedClassesIdConfigsConfigIdRunsRunIdIndexRouteImport } from './routes/_authenticated/classes.$id.configs.$configId.runs.$runId.index'
import { Route as AuthenticatedClassesIdConfigsConfigIdRunsRunIdDistributionsDistIdPresentRouteImport } from './routes/_authenticated/classes.$id.configs.$configId.runs.$runId.distributions.$distId.present'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const HowRoute = HowRouteImport.update({
  id: '/how',
  path: '/how',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const STokenRoute = STokenRouteImport.update({
  id: '/s/$token',
  path: '/s/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClassesIdRoute = AuthenticatedClassesIdRouteImport.update({
  id: '/classes/$id',
  path: '/classes/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClassesIdIndexRoute =
  AuthenticatedClassesIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedClassesIdRoute,
  } as any)
const AuthenticatedClassesIdConfigsConfigIdRoute =
  AuthenticatedClassesIdConfigsConfigIdRouteImport.update({
    id: '/configs/$configId',
    path: '/configs/$configId',
    getParentRoute: () => AuthenticatedClassesIdRoute,
  } as any)
const AuthenticatedClassesIdConfigsConfigIdIndexRoute =
  AuthenticatedClassesIdConfigsConfigIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedClassesIdConfigsConfigIdRoute,
  } as any)
const AuthenticatedClassesIdConfigsConfigIdRunsRunIdRoute =
  AuthenticatedClassesIdConfigsConfigIdRunsRunIdRouteImport.update({
    id: '/runs/$runId',
    path: '/runs/$runId',
    getParentRoute: () => AuthenticatedClassesIdConfigsConfigIdRoute,
  } as any)
const AuthenticatedClassesIdConfigsConfigIdRunsRunIdIndexRoute =
  AuthenticatedClassesIdConfigsConfigIdRunsRunIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedClassesIdConfigsConfigIdRunsRunIdRoute,
  } as any)
const AuthenticatedClassesIdConfigsConfigIdRunsRunIdDistributionsDistIdPresentRoute =
  AuthenticatedClassesIdConfigsConfigIdRunsRunIdDistributionsDistIdPresentRouteImport.update(
    {
      id: '/distributions/$distId/present',
      path: '/distributions/$distId/present',
      getParentRoute: () => AuthenticatedClassesIdConfigsConfigIdRunsRunIdRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/how': typeof HowRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/s/$token': typeof STokenRoute
  '/classes/$id': typeof AuthenticatedClassesIdRouteWithChildren
  '/classes/$id/': typeof AuthenticatedClassesIdIndexRoute
  '/classes/$id/configs/$configId': typeof AuthenticatedClassesIdConfigsConfigIdRouteWithChildren
  '/classes/$id/configs/$configId/': typeof AuthenticatedClassesIdConfigsConfigIdIndexRoute
  '/classes/$id/configs/$configId/runs/$runId': typeof AuthenticatedClassesIdConfigsConfigIdRunsRunIdRouteWithChildren
  '/classes/$id/configs/$configId/runs/$runId/': typeof AuthenticatedClassesIdConfigsConfigIdRunsRunIdIndexRoute
  '/classes/$id/configs/$configId/runs/$runId/distributions/$distId/present': typeof AuthenticatedClassesIdConfigsConfigIdRunsRunIdDistributionsDistIdPresentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/how': typeof HowRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/s/$token': typeof STokenRoute
  '/classes/$id': typeof AuthenticatedClassesIdIndexRoute
  '/classes/$id/configs/$configId': typeof AuthenticatedClassesIdConfigsConfigIdIndexRoute
  '/classes/$id/configs/$configId/runs/$runId': typeof AuthenticatedClassesIdConfigsConfigIdRunsRunIdIndexRoute
  '/classes/$id/configs/$configId/runs/$runId/distributions/$distId/present': typeof AuthenticatedClassesIdConfigsConfigIdRunsRunIdDistributionsDistIdPresentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/how': typeof HowRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/s/$token': typeof STokenRoute
  '/_authenticated/classes/$id': typeof AuthenticatedClassesIdRouteWithChildren
  '/_authenticated/classes/$id/': typeof AuthenticatedClassesIdIndexRoute
  '/_authenticated/classes/$id/configs/$configId': typeof AuthenticatedClassesIdConfigsConfigIdRouteWithChildren
  '/_authenticated/classes/$id/configs/$configId/': typeof AuthenticatedClassesIdConfigsConfigIdIndexRoute
  '/_authenticated/classes/$id/configs/$configId/runs/$runId': typeof AuthenticatedClassesIdConfigsConfigIdRunsRunIdRouteWithChildren
  '/_authenticated/classes/$id/configs/$configId/runs/$runId/': typeof AuthenticatedClassesIdConfigsConfigIdRunsRunIdIndexRoute
  '/_authenticated/classes/$id/configs/$configId/runs/$runId/distributions/$distId/present': typeof AuthenticatedClassesIdConfigsConfigIdRunsRunIdDistributionsDistIdPresentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/how'
    | '/dashboard'
    | '/s/$token'
    | '/classes/$id'
    | '/classes/$id/'
    | '/classes/$id/configs/$configId'
    | '/classes/$id/configs/$configId/'
    | '/classes/$id/configs/$configId/runs/$runId'
    | '/classes/$id/configs/$configId/runs/$runId/'
    | '/classes/$id/configs/$configId/runs/$runId/distributions/$distId/present'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/how'
    | '/dashboard'
    | '/s/$token'
    | '/classes/$id'
    | '/classes/$id/configs/$configId'
    | '/classes/$id/configs/$configId/runs/$runId'
    | '/classes/$id/configs/$configId/runs/$runId/distributions/$distId/present'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/how'
    | '/_authenticated/dashboard'
    | '/s/$token'
    | '/_authenticated/classes/$id'
    | '/_authenticated/classes/$id/'
    | '/_authenticated/classes/$id/configs/$configId'
    | '/_authenticated/classes/$id/configs/$configId/'
    | '/_authenticated/classes/$id/configs/$configId/runs/$runId'
    | '/_authenticated/classes/$id/configs/$configId/runs/$runId/'
    | '/_authenticated/classes/$id/configs/$configId/runs/$runId/distributions/$distId/present'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  HowRoute: typeof HowRoute
  STokenRoute: typeof STokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how': {
      id: '/how'
      path: '/how'
      fullPath: '/how'
      preLoaderRoute: typeof HowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$token': {
      id: '/s/$token'
      path: '/s/$token'
      fullPath: '/s/$token'
      preLoaderRoute: typeof STokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/classes/$id': {
      id: '/_authenticated/classes/$id'
      path: '/classes/$id'
      fullPath: '/classes/$id'
      preLoaderRoute: typeof AuthenticatedClassesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/classes/$id/': {
      id: '/_authenticated/classes/$id/'
      path: '/'
      fullPath: '/classes/$id/'
      preLoaderRoute: typeof AuthenticatedClassesIdIndexRouteImport
      parentRoute: typeof AuthenticatedClassesIdRoute
    }
    '/_authenticated/classes/$id/configs/$configId': {
      id: '/_authenticated/classes/$id/configs/$configId'
      path: '/configs/$configId'
      fullPath: '/classes/$id/configs/$configId'
      preLoaderRoute: typeof AuthenticatedClassesIdConfigsConfigIdRouteImport
      parentRoute: typeof AuthenticatedClassesIdRoute
    }
    '/_authenticated/classes/$id/configs/$configId/': {
      id: '/_authenticated/classes/$id/configs/$configId/'
      path: '/'
      fullPath: '/classes/$id/configs/$configId/'
      preLoaderRoute: typeof AuthenticatedClassesIdConfigsConfigIdIndexRouteImport
      parentRoute: typeof AuthenticatedClassesIdConfigsConfigIdRoute
    }
    '/_authenticated/classes/$id/configs/$configId/runs/$runId': {
      id: '/_authenticated/classes/$id/configs/$configId/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/classes/$id/configs/$configId/runs/$runId'
      preLoaderRoute: typeof AuthenticatedClassesIdConfigsConfigIdRunsRunIdRouteImport
      parentRoute: typeof AuthenticatedClassesIdConfigsConfigIdRoute
    }
    '/_authenticated/classes/$id/configs/$configId/runs/$runId/': {
      id: '/_authenticated/classes/$id/configs/$configId/runs/$runId/'
      path: '/'
      fullPath: '/classes/$id/configs/$configId/runs/$runId/'
      preLoaderRoute: typeof AuthenticatedClassesIdConfigsConfigIdRunsRunIdIndexRouteImport
      parentRoute: typeof AuthenticatedClassesIdConfigsConfigIdRunsRunIdRoute
    }
    '/_authenticated/classes/$id/configs/$configId/runs/$runId/distributions/$distId/present': {
      id: '/_authenticated/classes/$id/configs/$configId/runs/$runId/distributions/$distId/present'
      path: '/distributions/$distId/present'
      fullPath: '/classes/$id/configs/$configId/runs/$runId/distributions/$distId/present'
      preLoaderRoute: typeof AuthenticatedClassesIdConfigsConfigIdRunsRunIdDistributionsDistIdPresentRouteImport
      parentRoute: typeof AuthenticatedClassesIdConfigsConfigIdRunsRunIdRoute
    }
  }
}

interface AuthenticatedClassesIdConfigsConfigIdRunsRunIdRouteChildren {
  AuthenticatedClassesIdConfigsConfigIdRunsRunIdIndexRoute: typeof AuthenticatedClassesIdConfigsConfigIdRunsRunIdIndexRoute
  AuthenticatedClassesIdConfigsConfigIdRunsRunIdDistributionsDistIdPresentRoute: typeof AuthenticatedClassesIdConfigsConfigIdRunsRunIdDistributionsDistIdPresentRoute
}

const AuthenticatedClassesIdConfigsConfigIdRunsRunIdRouteChildren: AuthenticatedClassesIdConfigsConfigIdRunsRunIdRouteChildren =
  {
    AuthenticatedClassesIdConfigsConfigIdRunsRunIdIndexRoute:
      AuthenticatedClassesIdConfigsConfigIdRunsRunIdIndexRoute,
    AuthenticatedClassesIdConfigsConfigIdRunsRunIdDistributionsDistIdPresentRoute:
      AuthenticatedClassesIdConfigsConfigIdRunsRunIdDistributionsDistIdPresentRoute,
  }

const AuthenticatedClassesIdConfigsConfigIdRunsRunIdRouteWithChildren =
  AuthenticatedClassesIdConfigsConfigIdRunsRunIdRoute._addFileChildren(
    AuthenticatedClassesIdConfigsConfigIdRunsRunIdRouteChildren,
  )

interface AuthenticatedClassesIdConfigsConfigIdRouteChildren {
  AuthenticatedClassesIdConfigsConfigIdIndexRoute: typeof AuthenticatedClassesIdConfigsConfigIdIndexRoute
  AuthenticatedClassesIdConfigsConfigIdRunsRunIdRoute: typeof AuthenticatedClassesIdConfigsConfigIdRunsRunIdRouteWithChildren
}

const AuthenticatedClassesIdConfigsConfigIdRouteChildren: AuthenticatedClassesIdConfigsConfigIdRouteChildren =
  {
    AuthenticatedClassesIdConfigsConfigIdIndexRoute:
      AuthenticatedClassesIdConfigsConfigIdIndexRoute,
    AuthenticatedClassesIdConfigsConfigIdRunsRunIdRoute:
      AuthenticatedClassesIdConfigsConfigIdRunsRunIdRouteWithChildren,
  }

const AuthenticatedClassesIdConfigsConfigIdRouteWithChildren =
  AuthenticatedClassesIdConfigsConfigIdRoute._addFileChildren(
    AuthenticatedClassesIdConfigsConfigIdRouteChildren,
  )

interface AuthenticatedClassesIdRouteChildren {
  AuthenticatedClassesIdIndexRoute: typeof AuthenticatedClassesIdIndexRoute
  AuthenticatedClassesIdConfigsConfigIdRoute: typeof AuthenticatedClassesIdConfigsConfigIdRouteWithChildren
}

const AuthenticatedClassesIdRouteChildren: AuthenticatedClassesIdRouteChildren =
  {
    AuthenticatedClassesIdIndexRoute: AuthenticatedClassesIdIndexRoute,
    AuthenticatedClassesIdConfigsConfigIdRoute:
      AuthenticatedClassesIdConfigsConfigIdRouteWithChildren,
  }

const AuthenticatedClassesIdRouteWithChildren =
  AuthenticatedClassesIdRoute._addFileChildren(
    AuthenticatedClassesIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedClassesIdRoute: typeof AuthenticatedClassesIdRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedClassesIdRoute: AuthenticatedClassesIdRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  HowRoute: HowRoute,
  STokenRoute: STokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
